return {
    {
        name = "WezTerm",
        entries = {
            { keys = "Ctrl+h", desc = "Show shortcut palette in shell" },
            { keys = "Ctrl+Shift+h", desc = "Show shortcut palette" },
            { keys = "Ctrl+Shift+b", desc = "Next background image" },
            { keys = "Ctrl+Shift+L", desc = "Open link under mouse" },
            { keys = "Ctrl+Shift+>", desc = "Increase background brightness" },
            { keys = "Ctrl+Shift+<", desc = "Decrease background brightness" },
            { keys = "Ctrl+Shift+n", desc = "Toggle fullscreen" },
            { keys = "Ctrl+Shift+q", desc = "Quit WezTerm" },
        },
    },
    {
        name = "TMUX",
        entries = {
            { keys = "Prefix", desc = "Use Ctrl+a as prefix" },
            { keys = "Prefix+\\", desc = "Split pane horizontally" },
            { keys = "Prefix+/", desc = "Split pane vertically" },
            { keys = "Prefix+r", desc = "Reload tmux config" },
            { keys = "Prefix+h/j/k/l", desc = "Resize current pane" },
            { keys = "Prefix+c", desc = "Open new window in current path" },
            { keys = "Prefix+e", desc = "Open monthly notes in split pane" },
            { keys = "Prefix+o", desc = "Open daily todo in split pane" },
            { keys = "Prefix+v", desc = "Open Neovim in split pane" },
        },
    },
    {
        name = "TMUX copy",
        entries = {
            { keys = "v", desc = "Start selection" },
            { keys = "y", desc = "Copy selection" },
        },
    },
    {
        name = "NVIM",
        entries = {
            { keys = "Leader", desc = "Use Space as leader" },
            { keys = "Ctrl+h/j/k/l", desc = "Move between Vim and tmux panes" },
            { keys = "jk", desc = "Exit insert mode" },
            { keys = "Leader+p", desc = "Paste over selection without replacing yank" },
            { keys = "Leader+T", desc = "Toggle floating terminal" },
            { keys = "Leader+tw", desc = "Toggle line wrap" },
            { keys = "J (visual)", desc = "Move selected lines down" },
            { keys = "K (visual)", desc = "Move selected lines up" },
        },
    },
    {
        name = "NVIM find",
        entries = {
            { keys = "Leader+ff", desc = "Find files" },
            { keys = "Leader+pf", desc = "Find Git files" },
            { keys = "Leader+fg", desc = "Live grep" },
            { keys = "Leader+fG", desc = "Live grep hidden files" },
            { keys = "Leader+fb", desc = "List buffers" },
            { keys = "Leader+fh", desc = "Show help tags" },
            { keys = "Leader+fs", desc = "Prompt for grep search" },
        },
    },
    {
        name = "NVIM files",
        entries = {
            { keys = "Leader+v", desc = "Reveal file in Neo-tree" },
            { keys = "Leader+xx", desc = "Close Neo-tree" },
            { keys = "Leader+vv", desc = "Open parent directory in Oil" },
            { keys = "Leader+vf", desc = "Open Oil floating window" },
            { keys = "Leader+vi", desc = "Show Oil entry details" },
        },
    },
    {
        name = "NVIM LSP",
        entries = {
            { keys = "K", desc = "Show hover documentation" },
            { keys = "gd", desc = "Go to definition" },
            { keys = "gD", desc = "Go to declaration" },
            { keys = "gi", desc = "Go to implementation" },
            { keys = "gr", desc = "Show references" },
            { keys = "Leader+rn", desc = "Rename symbol" },
            { keys = "Leader+ca", desc = "Show code actions" },
            { keys = "Leader+fm", desc = "Show document symbols" },
        },
    },
    {
        name = "NVIM debug",
        entries = {
            { keys = "Leader+dt", desc = "Toggle breakpoint" },
            { keys = "Leader+dc", desc = "Continue debugger" },
        },
    },
    {
        name = "NVIM UI",
        entries = {
            { keys = "Leader+nt", desc = "Cycle Neovim theme" },
            { keys = "Leader+to", desc = "Toggle outline" },
            { keys = "Ctrl+e", desc = "Smooth scroll custom motion" },
            { keys = "Ctrl+d", desc = "Smooth scroll half page down" },
            { keys = "Ctrl+b", desc = "Smooth scroll page up" },
            { keys = "Ctrl+f", desc = "Smooth scroll page down" },
            { keys = "Ctrl+y", desc = "Smooth scroll up" },
            { keys = "Ctrl+u", desc = "Smooth scroll down" },
            { keys = "zt", desc = "Smooth scroll line to top" },
            { keys = "zz", desc = "Smooth scroll line to center" },
            { keys = "zb", desc = "Smooth scroll line to bottom" },
        },
    },
    {
        name = "NVIM Oil",
        entries = {
            { keys = "g?", desc = "Show Oil help" },
            { keys = "Enter", desc = "Open selected entry" },
            { keys = "Ctrl+t", desc = "Open entry in new tab" },
            { keys = "Ctrl+p", desc = "Preview entry in split" },
            { keys = "Ctrl+c", desc = "Close Oil" },
            { keys = "R", desc = "Refresh Oil" },
            { keys = "-", desc = "Go to parent directory" },
            { keys = "_", desc = "Open current working directory" },
            { keys = "`", desc = "Change directory to entry" },
            { keys = "~", desc = "Change tab directory to entry" },
            { keys = "gs", desc = "Change sort order" },
            { keys = "gx", desc = "Open entry with external app" },
            { keys = "H", desc = "Toggle hidden files" },
            { keys = "g\\", desc = "Toggle trash view" },
        },
    },
}
